name: Production Deployment API

on:
  push:
    branches: [ "main" ]

permissions:
  deployments: write
  contents: read
  statuses: write

jobs:
  check-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # CORREÇÃO AQUI: Passamos a ENV fake durante a instalação
      - name: Install dependencies
        run: npm ci
        env:
          DATABASE_URL: "postgresql://build:build@localhost:5432/build_db"

      # Esse passo agora é tecnicamente redundante pois o postinstall já rodou, 
      # mas mal não faz mantê-lo para garantir.
      - name: Generate Prisma Client
        run: npx prisma generate
        env:
           DATABASE_URL: "postgresql://build:build@localhost:5432/build_db"

      - name: Run Build
        run: npm run build
        env:
           DATABASE_URL: "postgresql://build:build@localhost:5432/build_db"

  deploy-production:
    needs: check-quality
    runs-on: ubuntu-latest
    if: success() 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger Coolify Deploy
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'

      - name: Create GitHub Deployment UI
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: '${{ github.token }}'
          environment-url: https://api.simplesagil.com.br
          environment: production
          initial-status: 'success'