name: Production Deployment UI

on:
  push:
    branches: [ "main" ]

# --- ADICIONE ESTE BLOCO ---
permissions:
  deployments: write
  contents: read
  statuses: write
# ---------------------------

jobs:
  update-github-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: '${{ github.token }}'
          environment-url: https://api.simplesagil.com.br
          environment: production
          initial-status: 'success'